In [3]:
import pandas as pd

product_df = pd.read_csv("./wconcept_data/wconcept_products_20260913_234742.csv")
review_df = pd.read_csv("./wconcept_data/wconcept_reviews_20260913_234742.csv")
blog_df = pd.read_csv("./wconcept_data/wconcept_blogs_20260914_001928.csv")

In [2]:
product_df.head()

,ranking_no,brand_name,product_name,original_price,sale_price,discount_rate,rating,review_count,like_count,product_id,product_url,img_url,category_depth1,category_depth2,category_depth3,category_depth4
0,1,틸아이다이,[단 하루!] [헤이가가 Pick]Wool cashmere V neck knit s...,137000.0,84728,38,5.0,29,5064,308886954,https://www.wconcept.co.kr/Product/308886954,https://product-image.wconcept.co.kr/productim...,여성,의류,니트,풀오버
1,2,드로우핏 우먼,[9/13 단 하루!] [W컨셉 단독][드로우핏우먼 X 주미니] 울 코튼 원턱 벨티...,87000.0,57855,33,5.0,13,804,308943720,https://www.wconcept.co.kr/Product/308943720,https://product-image.wconcept.co.kr/productim...,여성,의류,팬츠,슬랙스
2,3,마인드브릿지 우먼,"[주미니pick] 에센셜 브이넥 니트_6colors / 블랙,브라운,그레이,네이비,...",59900.0,25130,58,5.0,15,1604,308837675,https://www.wconcept.co.kr/Product/308837675,https://product-image.wconcept.co.kr/productim...,여성,의류,니트,풀오버
3,4,아비스파,[30%쿠폰] [단독]Davie 데이비 메리제인 스퀘어토 플랫슈즈(2way)_F35...,99000.0,54740,44,4.9,2273,9999,306035261,https://www.wconcept.co.kr/Product/306035261,https://product-image.wconcept.co.kr/productim...,여성,신발,플랫슈즈,메리제인
4,5,아워코모스,[48H 특가] cashmere deep V-neck knit (melange gr...,79000.0,49908,36,5.0,7,2802,308923689,https://www.wconcept.co.kr/Product/308923689,https://product-image.wconcept.co.kr/productim...,여성,의류,니트,풀오버

In [4]:
review_df.head()

,product_id,brand_name,product_name,product_url,review_page,review_no,reviewer,review_date,purchase_option,review_text,review_rating,evaluations,review_images
0,308886954,틸아이다이,[단 하루!] [헤이가가 Pick]Wool cashmere V neck knit s...,https://www.wconcept.co.kr/Product/308886954,1,1,ye******,2026.09.13,IVORY_FREE,예뻐요 빨리 추워져서 입고 나가고 싶어요 얼굴도 환하게 해주고 굿굿입니다,5.0,"{""사이즈"": ""적당함"", ""색상"": ""같음"", ""소재"": ""같음""}","[""https://media.wconcept.co.kr/review/30888695..."
1,308886954,틸아이다이,[단 하루!] [헤이가가 Pick]Wool cashmere V neck knit s...,https://www.wconcept.co.kr/Product/308886954,1,2,wc******,2026.09.13,IVORY_FREE,따둣해서 지금 입기좋아요 속에 옷은 신경써야될듯,5.0,"{""사이즈"": ""큼"", ""색상"": ""다름"", ""소재"": ""다름""}",[]
2,308886954,틸아이다이,[단 하루!] [헤이가가 Pick]Wool cashmere V neck knit s...,https://www.wconcept.co.kr/Product/308886954,1,3,he******,2026.09.12,IVORY_FREE,팔이 진짜 길긴 길어요ㅎㅎ 제 덩치에는 여리여리 한 느낌은 없지만 맨살에 괜찮고 잘...,4.0,"{""사이즈"": ""적당함"", ""색상"": ""같음"", ""소재"": ""비슷함""}","[""https://media.wconcept.co.kr/review/30888695..."
3,308886954,틸아이다이,[단 하루!] [헤이가가 Pick]Wool cashmere V neck knit s...,https://www.wconcept.co.kr/Product/308886954,1,4,wc******,2026.09.11,IVORY_FREE,아직 입고 나가진 않았지만 부드럽고 예뻐요~~,5.0,"{""사이즈"": ""적당함"", ""색상"": ""같음"", ""소재"": ""같음""}",[]
4,308886954,틸아이다이,[단 하루!] [헤이가가 Pick]Wool cashmere V neck knit s...,https://www.wconcept.co.kr/Product/308886954,1,5,ms******,2026.09.10,IVORY_FREE,촉감도 좋고 다 좋은데 기장이 많이 짧아요 특히 이너 나시는 진짜 너무 짧고 작아요 ㅠㅠ,5.0,"{""사이즈"": ""작음"", ""색상"": ""같음"", ""소재"": ""같음""}","[""https://media.wconcept.co.kr/review/30888695..."

In [5]:
blog_df.head()

,search_brand,title,link,description,bloggername,bloggerlink,postdate
0,틸아이다이,틸아이다이 26FW 신상 스트라이프 오버핏 티셔츠 가을 코디,https://blog.naver.com/serrri/224410585141,틸아이다이 TILLIDIE 26FW 신상 스트라이프 오버핏 티셔츠 가을 코디 스트라...,콩토루네,https://blog.naver.com/serrri,2026-09-14
1,틸아이다이,노운베러 KNOWNBETTER 여성 보트넥 니트 코디 가을 미니멀룩,https://blog.naver.com/jeeyha/224410344126,"요즘 매 시즌 옷이 출시되면 자연스럽게 찾아보게 되는 브랜드 틸아이다이, 프리버07...",패션뷰티 위드 위지,https://blog.naver.com/jeeyha,2026-09-13
2,틸아이다이,TILLIDIE 틸아이다이 26FW 신상 블라우스 추천 : Ribbon point ...,https://blog.naver.com/belle_0323/224409652928,소장각인 아이템이었어요 (만족하는 표정 ) 이 귀여운 블라우스를 포함해서 다양한 틸...,feelmore_createmore,https://blog.naver.com/belle_0323,2026-09-12
3,틸아이다이,"취향의 브랜드 가을옷 모음 - 킴지수, 더바넷, 러브바이무드, 틸아이....",https://blog.naver.com/frogrecord/224409344140,틸아이다이 Over-Fit utility jacket [TISP05JK10]_Win...,개구리 관찰일지,https://blog.naver.com/frogrecord,2026-09-12
4,틸아이다이,가을 쇼핑하고 싶은 선선해진 날씨 찜 또는 장바구니에 쏙 넣은 아....,https://blog.naver.com/pure_o_o/224408904922,"찜 ♥️ 또는 장바구니에 넣은 나의 취향저격 아이템 가을 쇼핑 하고 싶은 날, 아이...",향기로운 일상,https://blog.naver.com/pure_o_o,2026-09-12

In [ ]:
# pymysql vs mysql-connector-python

In [6]:
!pip install mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector-python in /Users/admin/Library/Python/3.9/lib/python/site-packages (9.4.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip

In [7]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="akzpxld12#4",
    database="wconcept_db_261001"
)

cursor = conn.cursor()

In [8]:
cursor

In [ ]:
conn.rollback() # 현재 커밋이 아직 안되었다 라는 전제하에서 초기로 일단 돌아온다

cursor.execute("SET FOREIGN_KEY_CHECKS = 0")
cursor.execute("TRUNCATE TABLE crawl_runs")
cursor.execute("SET FOREIGN_KEY_CHECKS = 1")

In [9]:
from datetime import datetime

collected_at = datetime.now()

SQL = """
INSERT INTO crawl_runs (collected_at) VALUES (%s)
"""

cursor.execute(SQL, (collected_at, ))

crawl_run_id = cursor.lastrowid

print("crawl_run_id : ", crawl_run_id)

crawl_run_id :  1

In [12]:
brand_names = product_df["brand_name"].dropna().drop_duplicates().to_list()
print(len(brand_names), brand_names)

89 ['틸아이다이', '드로우핏 우먼', '마인드브릿지 우먼', '아비스파', '아워코모스', '우이', '어스', '아디다스', '로브로브', '하우투러브미', '룩캐스트', '반원 아틀리에', '망고매니플리즈', '루에브르', '지지피엑스', '마르벳', '로트르드민', '오스트카카', '엽페', '라운드트리코', '모노로우', '무니드', '파사드패턴', '프론트로우', '르세지엠', '엔젤삭스', '자빈드서울', '더라우스트', '엘리자베스 스튜어트', '메무아', '꼼파뇨 키즈', '시티브리즈', '뉴발란스', '슬로우롤리', '바시카', '논앤논', '시야쥬', '수아레 우먼', '모한', '프렌치시크', '에임에이지 스튜디오', '언에디트', '세이지먼트', '앤하츠', '레브바이레브', '에토스', '씨씨콜렉트', '쎄씨', '르메메', '유메르', '제이청', '플로움', '마롭', '로우틸', '베르네프', '아틀리에 나인', '레테라', '올리브데올리브', '오디에르', '레이첼콕스', '사르투', '듀엘', '팁토이조이', '휠라', '드메리엘', '오프 앤드 어웨이', '문트', '비에이유 바이 브라이드앤유', '잇미샤', '마스 언 에브릴', '미드가르드', '아티드', '오브에르', '그레이데시온', '헌치', '아티카', '노노어', '프론투라인', '히비스커스블룸', '뮤니에', '주르티', '리드볼트', '토와브', '스퍼', '비올셋', '라메레이', '어나우트', '루시다', '시엔느']

In [13]:
SQL = """
INSERT INTO brands (brand_name) VALUES (%s)
ON DUPLICATE KEY UPDATE brand_name = VALUES(brand_name)
"""

In [14]:
for brand_name in brand_names :
    cursor.execute(SQL, (brand_name, ))

In [15]:
SQL = """
SELECT brand_id, brand_name FROM brands
"""

In [16]:
cursor.execute(SQL)

brand_rows = cursor.fetchall()
brand_rows

[(74, '그레이데시온'),
 (31, '꼼파뇨 키즈'),
 (77, '노노어'),
 (36, '논앤논'),
 (33, '뉴발란스'),
 (28, '더라우스트'),
 (62, '듀엘'),
 (2, '드로우핏 우먼'),
 (65, '드메리엘'),
 (86, '라메레이'),
 (20, '라운드트리코'),
 (45, '레브바이레브'),
 (60, '레이첼콕스'),
 (57, '레테라'),
 (9, '로브로브'),
 (54, '로우틸'),
 (17, '로트르드민'),
 (88, '루시다'),
 (14, '루에브르'),
 (11, '룩캐스트'),
 (49, '르메메'),
 (25, '르세지엠'),
 (82, '리드볼트'),
 (53, '마롭'),
 (16, '마르벳'),
 (70, '마스 언 에브릴'),
 (3, '마인드브릿지 우먼'),
 (13, '망고매니플리즈'),
 (30, '메무아'),
 (21, '모노로우'),
 (39, '모한'),
 (22, '무니드'),
 (67, '문트'),
 (80, '뮤니에'),
 (71, '미드가르드'),
 (35, '바시카'),
 (12, '반원 아틀리에'),
 (55, '베르네프'),
 (68, '비에이유 바이 브라이드앤유'),
 (85, '비올셋'),
 (61, '사르투'),
 (43, '세이지먼트'),
 (38, '수아레 우먼'),
 (84, '스퍼'),
 (34, '슬로우롤리'),
 (37, '시야쥬'),
 (89, '시엔느'),
 (32, '시티브리즈'),
 (48, '쎄씨'),
 (47, '씨씨콜렉트'),
 (8, '아디다스'),
 (4, '아비스파'),
 (5, '아워코모스'),
 (56, '아틀리에 나인'),
 (72, '아티드'),
 (76, '아티카'),
 (44, '앤하츠'),
 (87, '어나우트'),
 (7, '어스'),
 (42, '언에디트'),
 (41, '에임에이지 스튜디오'),
 (46, '에토스'),
 (26, '엔젤삭스'),
 (29, '엘리자베스 스튜어트'),
 (19, '엽페'),
 (59, '오디에르'),
 (73, '오브에르'),
 (18, '오스트카카'),
 (66, '오프 앤드 어웨이'),
 (58, '올리브데올리브'),
 (6, '우이'),
 (50, '유메르'),
 (69, '잇미샤'),
 (27, '자빈드서울'),
 (51, '제이청'),
 (81, '주르티'),
 (15, '지지피엑스'),
 (83, '토와브'),
 (1, '틸아이다이'),
 (63, '팁토이조이'),
 (23, '파사드패턴'),
 (40, '프렌치시크'),
 (78, '프론투라인'),
 (24, '프론트로우'),
 (52, '플로움'),
 (10, '하우투러브미'),
 (75, '헌치'),
 (64, '휠라'),
 (79, '히비스커스블룸')]

In [17]:
# dictionary comprehension => 딕셔너리 라는 자료구조를 손쉽게 만들 수 있도록 해주는 문법체계

brand_map = {brand_name: brand_id for brand_id, brand_name in brand_rows}
brand_map

{'그레이데시온': 74,
 '꼼파뇨 키즈': 31,
 '노노어': 77,
 '논앤논': 36,
 '뉴발란스': 33,
 '더라우스트': 28,
 '듀엘': 62,
 '드로우핏 우먼': 2,
 '드메리엘': 65,
 '라메레이': 86,
 '라운드트리코': 20,
 '레브바이레브': 45,
 '레이첼콕스': 60,
 '레테라': 57,
 '로브로브': 9,
 '로우틸': 54,
 '로트르드민': 17,
 '루시다': 88,
 '루에브르': 14,
 '룩캐스트': 11,
 '르메메': 49,
 '르세지엠': 25,
 '리드볼트': 82,
 '마롭': 53,
 '마르벳': 16,
 '마스 언 에브릴': 70,
 '마인드브릿지 우먼': 3,
 '망고매니플리즈': 13,
 '메무아': 30,
 '모노로우': 21,
 '모한': 39,
 '무니드': 22,
 '문트': 67,
 '뮤니에': 80,
 '미드가르드': 71,
 '바시카': 35,
 '반원 아틀리에': 12,
 '베르네프': 55,
 '비에이유 바이 브라이드앤유': 68,
 '비올셋': 85,
 '사르투': 61,
 '세이지먼트': 43,
 '수아레 우먼': 38,
 '스퍼': 84,
 '슬로우롤리': 34,
 '시야쥬': 37,
 '시엔느': 89,
 '시티브리즈': 32,
 '쎄씨': 48,
 '씨씨콜렉트': 47,
 '아디다스': 8,
 '아비스파': 4,
 '아워코모스': 5,
 '아틀리에 나인': 56,
 '아티드': 72,
 '아티카': 76,
 '앤하츠': 44,
 '어나우트': 87,
 '어스': 7,
 '언에디트': 42,
 '에임에이지 스튜디오': 41,
 '에토스': 46,
 '엔젤삭스': 26,
 '엘리자베스 스튜어트': 29,
 '엽페': 19,
 '오디에르': 59,
 '오브에르': 73,
 '오스트카카': 18,
 '오프 앤드 어웨이': 66,
 '올리브데올리브': 58,
 '우이': 6,
 '유메르': 50,
 '잇미샤': 69,
 '자빈드서울': 27,
 '제이청': 51,
 '주르티': 81,
 '지지피엑스': 15,
 '토와브': 83,
 '틸아이다이': 1,
 '팁토이조이': 63,
 '파사드패턴': 23,
 '프렌치시크': 40,
 '프론투라인': 78,
 '프론트로우': 24,
 '플로움': 52,
 '하우투러브미': 10,
 '헌치': 75,
 '휠라': 64,
 '히비스커스블룸': 79}

In [18]:
PRODUCT_SQL = """
INSERT INTO products (
    product_id,
    brand_id,
    product_name,
    product_url,
    img_url,
    category_depth1,
    category_depth2,
    category_depth3,
    category_depth4
)
VALUES (
    %s, %s, %s, %s, %s,
    %s, %s, %s, %s
)
ON DUPLICATE KEY UPDATE
    brand_id = VALUES(brand_id),
    product_name = VALUES(product_name),
    product_url = VALUES(product_url),
    img_url = VALUES(img_url),
    category_depth1 = VALUES(category_depth1),
    category_depth2 = VALUES(category_depth2),
    category_depth3 = VALUES(category_depth3),
    category_depth4 = VALUES(category_depth4)
"""

In [19]:
# 유틸리티 함수를 생성 & 사용
# 기존에 크롤링을 통해서 수집한 데이터 가운데 비어있는 = 결측치값이 존재하는 경우를 대비한 함수
# 파이썬 > 팬더스 > 결측치의 값이 NULL -> NaN, NaT // MySQL : None
import pandas as pd

def to_none(value) :
    if pd.isna(value) :
        return None
    return value

def to_date(value) :
    if pd.isna(value) :
        return None

    if isinstance(value, pd.Timestamp) :
        return value.date()
    return value

In [20]:
for _, row in product_df.iterrows() :
    product_id = str(row["product_id"])
    brand_id = brand_map.get(row["brand_name"])

    cursor.execute(
        PRODUCT_SQL,
        (
            product_id,
            brand_id,
            to_none(row["product_name"]),
            to_none(row["product_url"]),
            to_none(row["img_url"]),
            to_none(row["category_depth1"]),
            to_none(row["category_depth2"]),
            to_none(row["category_depth3"]),
            to_none(row["category_depth4"])            
        )
    )

In [21]:
SNAPSHOT_SQL = """
INSERT INTO product_snapshots (
    crawl_run_id,
    product_id,
    original_price,
    sale_price,
    discount_rate,
    rating,
    review_count,
    like_count
)
VALUES (
    %s, %s, %s, %s,
    %s, %s, %s, %s
)
ON DUPLICATE KEY UPDATE
    original_price = VALUES(original_price),
    sale_price = VALUES(sale_price),
    discount_rate = VALUES(discount_rate),
    rating = VALUES(rating),
    review_count = VALUES(review_count),
    like_count = VALUES(like_count)
"""

In [22]:
for _, row in product_df.iterrows() :
    cursor.execute(
        SNAPSHOT_SQL,
        (
            crawl_run_id,
            str(row["product_id"]),
            to_none(row["original_price"]),
            to_none(row["sale_price"]),
            to_none(row["discount_rate"]),
            to_none(row["rating"]),
            to_none(row["review_count"]),
            to_none(row["like_count"])
        )
    )

In [23]:
RANKING_SQL = """
INSERT INTO product_rankings (
    crawl_run_id,
    product_id,
    ranking_no
)
VALUES (
    %s, %s, %s
)
ON DUPLICATE KEY UPDATE
    ranking_no = VALUES(ranking_no)
"""

In [24]:
for _, row in product_df.iterrows() :
    cursor.execute(
        RANKING_SQL,
        (
            crawl_run_id,
            str(row["product_id"]),
            int(row["ranking_no"])
        )
    )

In [33]:
REVIEW_SQL = """
INSERT INTO reviews (
    crawl_run_id,
    product_id,
    review_page,
    review_no,
    reviewer,
    review_date,
    purchase_option,
    review_text,
    review_rating
)
VALUES (
    %s, %s, %s, %s, %s,
    %s, %s, %s, %s
)
ON DUPLICATE KEY UPDATE
    review_id = LAST_INSERT_ID(review_id),
    review_page = VALUES(review_page),
    review_no = VALUES(review_no),
    reviewer = VALUES(reviewer),
    review_date = VALUES(review_date),
    purchase_option = VALUES(purchase_option),
    review_text = VALUES(review_text),
    review_rating = VALUES(review_rating)
"""

In [26]:
EVALUATION_SQL = """
INSERT INTO review_evaluations (
    review_id,
    evaluation_type,
    evaluation_value
)
VALUES (
    %s, %s, %s
)
ON DUPLICATE KEY UPDATE
    evaluation_type = VALUES(evaluation_type),
    evaluation_value = VALUES(evaluation_value)
"""

In [27]:
IMAGE_SQL = """
INSERT INTO review_images (
    review_id,
    image_url
)
VALUES (
    %s, %s
)
ON DUPLICATE KEY UPDATE
    image_url = VALUES(image_url)
"""

In [29]:
print(type(review_df.loc[0, "evaluations"]))
print(type(review_df.loc[0, "review_images"]))

<class 'str'>
<class 'str'>

In [30]:
# Abstract Syntax Tree = 추상 구문 트리
# {"사이즈": "적당함", "색상": "같음", "소재": "같음"}	["https://media.wconcept.co.kr/review/30888695...

# {"사이즈": -> 딕셔너리 자료구조 , 키
# "적당함", -> 값
# "색상":
# "같음",
# "소재":
# "같음"}

import pandas as pd
import ast

review_df["evaluations"] = review_df["evaluations"].apply(
    lambda x: ast.literal_eval(x)
    if pd.notna(x)
    else {}
)

review_df["review_images"] = review_df["review_images"].apply(
    lambda x: ast.literal_eval(x)
    if pd.notna(x)
    else []
)

In [31]:
print(type(review_df.loc[0, "evaluations"]))
print(type(review_df.loc[0, "review_images"]))

<class 'dict'>
<class 'list'>

In [34]:
for _, row in review_df.iterrows() :
    cursor.execute(
        REVIEW_SQL,
        (
            crawl_run_id,
            str(row["product_id"]),
            int(row["review_page"]),
            int(row["review_no"]),
            to_none(row["reviewer"]),
            to_date(row["review_date"]),
            to_none(row["purchase_option"]),
            to_none(row["review_text"]),
            to_none(row["review_rating"])
        )
    )

    review_id = cursor.lastrowid

    evaluations = row["evaluations"]

    if isinstance(evaluations, dict) :
        for evaluation_type, evaluation_value in evaluations.items() :
            cursor.execute(
                EVALUATION_SQL,
                (
                    review_id,
                    evaluation_type,
                    evaluation_value
                )
            )
            
    review_images = row["review_images"]

    if isinstance(review_images, list) :
        for image_url in review_images :

            if not image_url :
                continue
                
            cursor.execute(
                IMAGE_SQL,
                (
                    review_id,
                    image_url
                )
            )

In [35]:
BLOG_SQL = """
INSERT INTO blog_posts (
    crawl_run_id,
    brand_id,
    search_brand,
    title,
    link,
    description,
    bloggername,
    bloggerlink,
    postdate
)
VALUES (
    %s, %s, %s, %s, %s,
    %s, %s, %s, %s
)
ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    link = VALUES(link),
    description = VALUES(description),
    bloggername = VALUES(bloggername),
    bloggerlink = VALUES(bloggerlink),
    postdate = VALUES(postdate)
"""

In [36]:
for _, row in blog_df.iterrows() :
    brand_id = brand_map.get(row["search_brand"])

    if brand_id is None :
        continue

    cursor.execute(
        BLOG_SQL,
        (
            crawl_run_id,
            brand_id,
            to_none(row["search_brand"]),
            to_none(row["title"]),
            to_none(row["link"]),
            to_none(row["description"]),
            to_none(row["bloggername"]),
            to_none(row["bloggerlink"]),
            to_date(row["postdate"])
        )
    )

In [37]:
try :
    conn.commit()
    print("✅ 전체 데이터 저장 완료!")
except Exception as e :
    conn.rollback()
    print("❌ 오류 발생!")
    print(e)
finally :
    cursor.close()
    conn.close()

✅ 전체 데이터 저장 완료!